### ISSUE TITLE
Audio does not play on "START" button press

### ISSUE THREAD

**Issue by DAB0mB** [selkies-project/selkies#131]
If I press randomly on other elements on the screen before the playback loads, the video and audio would start autoplaying as soon as the connection is ready without any issues. If no mouse event was triggered during playback load, the "START" button will show, but when I press on it, only the video would start playing, not the audio. I believe it's not a WebRTC issue, because when I grab the audio element "audio.audio" and call the `audio.play()` method, it would actually start playing. Maybe by calling `playAudio()` on "START" button "click" event, would solve the issue (see [code](https://github.com/selkies-project/selkies-gstreamer/blob/cb6b2de7592b7ebdc77578de1ddde48e4b74c651/addons/gst-web/src/index.html#L382)).

**Comment by ehfd** [comment]
Associated with #109.

**Comment by ehfd** [comment]
Applied a fix in https://github.com/selkies-project/selkies-gstreamer/commit/6d16d0052a4ec80e136996d7634c68a2cb350a90.
Need to test.

**Comment by ehfd** [comment]
@DAB0mB Please test the fix this works for you as well (latest `ghcr.io/selkies-project/selkies-gstreamer/gst-py-example:main-ubuntu20.04` or ghcr.io/selkies-project/selkies-gstreamer/gst-py-example:main-ubuntu22.04).

**Comment by ehfd** [comment]
I understand that the issue was fixed. Please reopen if it was not.

**Comment by ehfd** [comment]
#109 still has issues.
