### ISSUE TITLE
Doesn't work on firefox. Chrome works fine

### ISSUE THREAD

**Issue by ghost** [selkies-project/selkies#18]
It seems that selkies-gstreamer will stuck on `Waiting for video stream ` on Firefox 96.

The status message only shows 
``
[19:0:0] [signalling] Connecting to server.
[19:0:2] [signalling] Registering with server, peer ID: 1
[19:0:4] [signalling] Registered with server.
[19:0:4] [signalling] Waiting for video stream.
[19:0:6] [webrtc] [ERROR] attempt to send data channel message before channel was open.
[19:0:6] [webrtc] Received incoming video stream from peer
[19:0:6] [webrtc] Received incoming audio stream from peer
[19:0:7] [webrtc] [ERROR] attempt to send data channel message before channel was open.

``

**Comment by xhejtman** [comment]
This is because remote SDP offer contains H264 video while firefox responds with VP8 reply. gstreamer gives up in this case.

**Comment by ehfd** [comment]
Is this still an issue?

**Comment by ehfd** [comment]
https://www.plumislandmedia.net/something-i-learned/firefox-has-limited-ability-to-handle-h-264/
Probably associated with this.

**Comment by ehfd** [comment]
Profile in gstwebrtc_app.py is set to "high" and therefore this should be the issue. @danisla What are the implications of changing the profile to "constrained-baseline"?

**Comment by ehfd** [comment]
More references:
https://stackoverflow.com/questions/70652697/webrtc-using-gstreamer-and-webrtcbin-works-with-vp9-but-not-with-h264
https://stackoverflow.com/questions/68060965/simple-webrtc-webpage-works-well-in-chrome-and-safari-but-not-in-firefox
https://groups.google.com/g/mozilla.dev.media/c/Ye29vuMTpo8
This might indicate that the high profile may work when the above is fixed?:
https://bugzilla.mozilla.org/show_bug.cgi?id=1755361

**Comment by apas11** [comment]
Fix for Firefox users
If you’re stuck with black video / high CPU in WebRTC sessions:

about:config → media.webrtc.hw.h264.enabled → true  

This enables hardware-accelerated H.264 for WebRTC in Firefox. Solves GStreamer + Firefox issues for me on Linux. Confirmed working with Selkies streaming (no more “blank video” or fallback to VP8).
