### ISSUE TITLE
Use a simple HEAD request to resolve tags to digests

### ISSUE THREAD

**Issue by jonjohnsonjr** [selkies-project/selkies#2]
You're calling list tags in order to determine the digest of an image [here](https://github.com/selkies-project/selkies/blob/e17052e33374be0ba3bc3942f1698ff18c89dcf6/images/controller/cmd/image_puller/image_puller.go#L237-L278).

It is much cheaper for the registry to serve a simpler `HEAD /v2/<repo>/manifests/<tag>` request instead of producing the entire tags list response.

In some situations (e.g. if you need to resolve 100 tags in a single repository), it might be cheaper to do this by listing tags, but you don't appear to be deduping these `findImageTags` calls by their repository. You could cache the response by repo and re-use that for subsequent checks, but I would guess that the `HEAD` calls will average out to be cheaper in almost any circumstance.

I maintain a library that does most of the things you're doing, e.g. [`google.List`](https://godoc.org/github.com/google/go-containerregistry/pkg/v1/google#List), [`google.NewEnvAuthenticator`](https://godoc.org/github.com/google/go-containerregistry/pkg/v1/google#NewEnvAuthenticator), and [`remote.Head`](https://godoc.org/github.com/google/go-containerregistry/pkg/v1/remote#Head) should cover most of it.

**Comment by danisla** [comment]
@jonjohnsonjr thanks for suggestions, PR #4 implements the suggested improvements.

**Comment by jonjohnsonjr** [comment]
Thanks, I really appreciate it! Left one comment on the PR, but otherwise LGTM.
