### ISSUE TITLE
Any production dependencies on non-`master` branches?

### ISSUE THREAD

**Issue by JanCVanB** [selkies-project/selkies#21]
I'm planning to delete every branch other than `master`, since they're all either behind (`pull-secrets`, `dev`), abandoned (`app-launcher-pwa-1`, `dependabot/npm_and_yarn/images/gce-proxy/src/http-proxy-1.18.1`), or replaced by a tag (`v1.0.0`). Do we know of any production/live environments that depend on those branches?

**Comment by danisla** [comment]
These can be removed:
- app-launcher-pwa-1
- dependabot/npm_and_yarn/images/gce-proxy/src/http-proxy-1.18.1
- pull-secrets

Keep the `dev` branch around though, we'll use that as gitflow to master.

**Comment by JanCVanB** [comment]
@danisla Do we need to test that it's safe to delete the `v1.0.0` branch, now that there's a `v1.0.0` tag for the same commit?

I've deleted `app-launcher-pwa-1`, `dependabot/npm_and_yarn/images/gce-proxy/src/http-proxy-1.18.1`, and `pull-secrets`.
I've fast-forwarded `dev` to meet `master`.

**Comment by danisla** [comment]
@JanCVanB yes should be safe to delete the v1.0.0 branch.

**Comment by JanCVanB** [comment]
Thanks. Now all of our branches are up-to-date!
