### ISSUE TITLE
Rename to `selkies-core`?

### ISSUE THREAD

**Issue by JanCVanB** [selkies-project/selkies#32]
This would reinforce to users that this repo is not the entirety of "the Selkies project/platform", and it would make writing/reading/talking about this repo less ambiguous.

**Comment by danisla** [comment]
Wouldn't this hurt discoverability? It's nice to have some singular repo that has the same title as the project, even if it doesn't contain every component. I would rather keep it `selkies`

**Comment by JanCVanB** [comment]
Good point. Let's keep the repo name `selkies`, and then we'll keep a lookout for opportunities when it makes sense to append `-core` (maybe images/artifacts or otherwise non-SEO things).
