### ISSUE TITLE
Find a way to use Gamepad controllers without external container privileges

### ISSUE THREAD

**Issue by ehfd** [selkies-project/selkies#55]
Currently, selkies-gstreamer does support gamepads only when the uinput device is provisioned. This is very cumbersome and risky in Kubernetes.

Instead of using that, it may be possible to directly translate them to Xorg operations (and later Wayland #46 using [virtual keyboard](https://wayland.app/protocols/virtual-keyboard-unstable-v1)).

Relevant files: [gst-web](https://github.com/selkies-project/selkies-gstreamer/tree/master/addons/gst-web/src) module and [webrtc_input.py](https://github.com/selkies-project/selkies-gstreamer/blob/master/src/selkies_gstreamer/webrtc_input.py).

**Comment by ehfd** [comment]
Requires a careful assessment of the coordination with a Gamepad input and transforming them into keyboard or mouse signals or using [xserver-xorg-input-joystick](https://manpages.debian.org/testing/xserver-xorg-input-joystick/joystick.4.en.html) without using modprobe or touching the kernel.

**Comment by ehfd** [comment]
It's not impossible to just translate the Gamepad API signal within the browser and then pass like it was a keystroke, as long as careful tuning is done.

A couple of programs exist to map gamepad buttons to keyboard keys, including:

[qjoypad](https://aur.archlinux.org/packages/qjoypad/)AUR
[antimicrox](https://aur.archlinux.org/packages/antimicrox/)AUR
[sc-controller](https://aur.archlinux.org/packages/sc-controller/)AUR
[steam](https://archlinux.org/packages/?name=steam) - see [Steam#Steam Input](https://wiki.archlinux.org/title/Steam#Steam_Input)
All work well without the need for additional X.org configuration.

https://wiki.archlinux.org/title/Gamepad

**Comment by loochek** [comment]
If you are interested, I can suggest an another approach for games running under Wine. I've written a [small Xinput reimplementation](https://github.com/loochek/wine-vpad/) that acts like a virtual Xbox gamepad and can be controlled from host Linux environment via a named pipe. So, I've successfully paired it with your project (I can provide dirty rewritten version of webrtc_input.py). As games are often run under Wine, my solution is applicable quite widely and is much better than translating gamepad input to the keyboard and mouse.

**Comment by ehfd** [comment]
@loochek Hi! Thanks for bringing this up for us! We are short of hands, so this is a bit behind priority for us now. If you can provide us your webrtc_input.py file, someone might be able to clean it so that it doesn't collide with existing flows and make a PR for us.
Thanks a lot for implementing this solution.

**Comment by loochek** [comment]
@ehfd [webrtc_input.py](https://gist.github.com/loochek/f0d875fb8c2adcb92431e13868cbd079)
Basically I just replaced the logic in `__js_connect` and `__js_emit` with my own

**Comment by ehfd** [comment]
Thanks! @loochek

**Comment by JinhuaSu** [comment]
> @ehfd [webrtc_input.py](https://gist.github.com/loochek/f0d875fb8c2adcb92431e13868cbd079) Basically I just replaced the logic in `__js_connect` and `__js_emit` with my own

Thanks! It works on me. 
Binding of Issac: XBOX mode
Genshin Impact: USB controller mode

**Comment by ehfd** [comment]
Update: Perhaps, try using https://github.com/ValveSoftware/gamescope as an alternative.

https://github.com/akdor1154/gamescope-pkg

**Comment by ehfd** [comment]
Relevant: https://web.archive.org/web/20211003152946/https://parsec.app/blog/game-streaming-tech-in-the-browser-with-parsec-5b70d0f359bc

**Comment by danisla** [comment]
Selkies already uses the HTML5 Gamepad API, so there is nothing to change.

I am not aware of any way to support gamepads without uinput, Joystick events are not handled by Xorg.

**Comment by ehfd** [comment]
1. Perhaps, find some kind of a way to create a synthetic `/dev/input/*` device that passes input from HTML5 without  `/dev/uinput` (or an emulated `/dev/uinput`). I agree this is hard.

[Alternative to evdev](http://who-t.blogspot.com/2016/05/the-difference-between-uinput-and-evdev.html): [perhaps joydev](https://stackoverflow.com/a/62393404)?

2. If not number 1, you are right. The only other option to joystick events with uinput is to replace them with cursor/key events. Since we already are obtaining input with the HTML5 Gamepad API, it would be easier to just translate them to key events.

> joystick is an Xorg input driver for controlling the pointer with a joystick device.
> 
> [Use this driver, if you want to](https://manpages.debian.org/testing/xserver-xorg-input-joystick/joystick.4.en.html#Use)
> - generate cursor movement, perform button or key events to control desktop and applications
> - generate cursor key events for playing legacy games, that have no native joystick support
> 
> [Do not use, if you want to](https://manpages.debian.org/testing/xserver-xorg-input-joystick/joystick.4.en.html#Do)
> - play games, that have native joystick support
> - use XI2 applications. The [evdev(4)](https://manpages.debian.org/testing/xserver-xorg-input-evdev/evdev.4.en.html) driver will suffice for those in most cases.

3. Even when the above options are exhausted, it would be possible to improve things at least within Wine. There are applications that simply do not input correctly [even using a mouse in Wine](https://github.com/selkies-project/selkies-gstreamer/issues/28#issuecomment-1277196623).

https://github.com/loochek/wine-vpad/
https://gist.github.com/loochek/f0d875fb8c2adcb92431e13868cbd079

Either way, I'm still keeping this issue open.

The documentation to use uinput in bare metal is still required. #90 #28

**Comment by danisla** [comment]
I’m looking into ways to emulate the js0 evdev with an LD_PRELOAD shim. Something that will intercept the syscalls and connect to the Selkies gstreamer app.

**Comment by ehfd** [comment]
> I’m looking into ways to emulate the js0 evdev with an LD_PRELOAD shim. Something that will intercept the syscalls and connect to the Selkies gstreamer app. 

Something similar to VirtualGL's internal mechanics, I guess.

**Comment by ehfd** [comment]
We have a completely novel implementation of gamepad support in containers with #95.
Please leave a message here or in the Discord if you would like to help test Wine applications.
