### ISSUE TITLE
x265enc feature

### ISSUE THREAD

**Issue by GabrieleRisso** [selkies-project/selkies#67]
Hello, I've seen that part of the implementation for  "nvfbchevcenc" is done but currently can not be part of the pipeline:

https://github.com/CERIT-SC/webrtc/blob/3ae73f4c7ffc5d08e5957e7aec60f03a1e6cf774/streamer/gstwebrtc_app.py#L176

elif self.encoder in ["nvfbch264enc", "nvfbchevcenc"]:
            pass
        else:
            raise GSTWebRTCAppError("Unsupported encoder for pipeline: %s" % self.encoder)

how can I help to make it work?

**Comment by ehfd** [comment]
This is not within the realm of the project right now. Please come to the [Discord](https://discord.gg/wDNGDeSW5F) and ask @xhejtman about it if you want to go with it... 

Duplicate to https://github.com/selkies-project/selkies-gstreamer/issues/30.

**Comment by ehfd** [comment]
Plus, h265 is not possible in WebRTC now. We can try it out if we have WebTransport.

**Comment by ehfd** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3408
