### ISSUE TITLE
Screen tearing in all encoders sometimes

### ISSUE THREAD

**Issue by ehfd** [selkies-project/selkies#71]
Reproducible both with nvh264enc and x264enc. Possibly issues with GStreamer configurations or the X11 capturer.

Happens every few dozen minutes or hours.

For now, changing the bitrate then changing it back fixes it. Disabling the compositor also might help.

Screenshots will come up.

**Comment by ehfd** [comment]
![image](https://user-images.githubusercontent.com/8457324/212474781-f8983ee6-54ff-49a2-9899-3c209525fe3d.png)

**Comment by ehfd** [comment]
x264enc:
```0:01:03.809454590 29935 0x5594ca7e56a0 WARN                 x264enc gstx264enc.c:1273:gst_x264_enc_log_callback:<x264enc> VBV underflow (frame 2698, -36563 bits)```

**Comment by vamman** [comment]
I have been seeing some significant screen tearing here in 3D. Not seeing it nearly as much on the desktop. It looks like a classic vsync issue but I'm not convinced it is.

**Comment by ehfd** [comment]
No longer happens as frequently, although #78 is back.
